[2023-07-15 00:00:08,128] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.crear_tabla scheduled__2023-07-14T00:00:00+00:00 [queued]>
[2023-07-15 00:00:08,218] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.crear_tabla scheduled__2023-07-14T00:00:00+00:00 [queued]>
[2023-07-15 00:00:08,220] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-15 00:00:08,222] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-15 00:00:08,224] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-15 00:00:08,324] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): crear_tabla> on 2023-07-14 00:00:00+00:00
[2023-07-15 00:00:08,335] {standard_task_runner.py:52} INFO - Started process 25138 to run task
[2023-07-15 00:00:08,353] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_con_conexion_postgres', 'crear_tabla', 'scheduled__2023-07-14T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmpo0p0amc0', '--error-file', '/tmp/tmpjxlrgq_t']
[2023-07-15 00:00:08,356] {standard_task_runner.py:80} INFO - Job 45: Subtask crear_tabla
[2023-07-15 00:00:08,531] {task_command.py:371} INFO - Running <TaskInstance: dag_con_conexion_postgres.crear_tabla scheduled__2023-07-14T00:00:00+00:00 [running]> on host bd4a51b00e09
[2023-07-15 00:00:14,425] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_con_conexion_postgres
AIRFLOW_CTX_TASK_ID=crear_tabla
AIRFLOW_CTX_EXECUTION_DATE=2023-07-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-14T00:00:00+00:00
[2023-07-15 00:00:14,430] {logging_mixin.py:115} INFO - creando conexion
[2023-07-15 00:00:14,540] {script_etl.py:20} INFO - DB_USER probando usuario 2: bapintor_coderhouse
[2023-07-15 00:00:14,543] {logging_mixin.py:115} INFO - usuario probando 2 bapintor_coderhouse
[2023-07-15 00:00:15,967] {logging_mixin.py:115} INFO - Conexi√≥n exitosa a la base de datos
[2023-07-15 00:00:16,450] {python.py:173} INFO - Done. Returned value was: None
[2023-07-15 00:00:16,573] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=dag_con_conexion_postgres, task_id=crear_tabla, execution_date=20230714T000000, start_date=20230715T000008, end_date=20230715T000016
[2023-07-15 00:00:16,890] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-07-15 00:00:17,098] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-16 18:26:27,223] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.crear_tabla scheduled__2023-07-14T00:00:00+00:00 [queued]>
[2023-07-16 18:26:27,652] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.crear_tabla scheduled__2023-07-14T00:00:00+00:00 [queued]>
[2023-07-16 18:26:27,662] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:26:27,668] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-16 18:26:27,672] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:26:28,243] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): crear_tabla> on 2023-07-14 00:00:00+00:00
[2023-07-16 18:26:28,370] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_con_conexion_postgres', 'crear_tabla', 'scheduled__2023-07-14T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmpgofmp8v8', '--error-file', '/tmp/tmpxrs3960q']
[2023-07-16 18:26:28,356] {standard_task_runner.py:52} INFO - Started process 55443 to run task
[2023-07-16 18:26:28,408] {standard_task_runner.py:80} INFO - Job 57: Subtask crear_tabla
[2023-07-16 18:26:32,274] {task_command.py:371} INFO - Running <TaskInstance: dag_con_conexion_postgres.crear_tabla scheduled__2023-07-14T00:00:00+00:00 [running]> on host bd4a51b00e09
[2023-07-16 18:31:28,418] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_con_conexion_postgres
AIRFLOW_CTX_TASK_ID=crear_tabla
AIRFLOW_CTX_EXECUTION_DATE=2023-07-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-14T00:00:00+00:00
[2023-07-16 18:31:30,022] {logging_mixin.py:115} INFO - creando conexion
[2023-07-16 18:31:31,755] {local_task_job.py:221} WARNING - State of this instance has been externally set to None. Terminating instance.
[2023-07-16 18:31:32,175] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 55443. PIDs of all processes in the group: [55443]
[2023-07-16 18:31:32,280] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 55443
[2023-07-16 18:31:32,343] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-07-16 18:31:32,364] {variable.py:272} ERROR - Unable to retrieve variable from secrets backend (MetastoreBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 265, in get_variable_from_secrets
    var_val = secrets_backend.get_variable(key=key)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/metastore.py", line 63, in get_variable
    var_value = session.query(Variable).filter(Variable.key == key).first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2893, in _iter
    statement = self._statement_20()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 422, in _statement_20
    if self.dispatch.before_compile:
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/event/base.py", line 321, in __get__
    disp = self.dispatch._for_instance(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/event/base.py", line 125, in _for_instance
    def _for_instance(self, instance):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1563, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-07-16 18:31:32,676] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script_etl.py", line 38, in create_table
    connection = create_connection()
  File "/opt/airflow/dags/script_etl.py", line 17, in create_connection
    db_host = Variable.get("DB_HOST")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 138, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable DB_HOST does not exist'
[2023-07-16 18:31:33,052] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag_con_conexion_postgres, task_id=crear_tabla, execution_date=20230714T000000, start_date=20230716T182627, end_date=20230716T183133
[2023-07-16 18:31:35,735] {standard_task_runner.py:97} ERROR - Failed to execute job 57 for task crear_tabla ('Variable DB_HOST does not exist'; 55443)
[2023-07-16 18:31:38,304] {process_utils.py:75} INFO - Process psutil.Process(pid=55443, status='terminated', exitcode=1, started='18:26:27') (55443) terminated with exit code 1
